### ISSUE TITLE
Is this compatible with the latest version of Angular2 and Angular CLI?

### ISSUE THREAD

**Issue by gh0st** [mraible/ng2-demo#9]
The title of the article on DZone is *Getting Started and Testing With Angular CLI and Angular 2 (RC5) — Part 2*, but RC5 is long gone I think and some of the structure is a touch different now. Is this Github version the most up-to-date tutorial?

**Comment by mraible** [comment]
Yep! I updated the tutorial for the latest release of Angular CLI
yesterday. The code is all up-to-date, but I still need to do minor updates
to README.adoc. See the commit log for recent changes.
